app_google.google_callback:
    path:  /google/oauthcallback
    defaults: { _controller: GoogleBundle:Google:callback }

app_google.google_disconnect:
    path:  /google/disconnect
    defaults: { _controller: GoogleBundle:Google:disconnect }