services:
  app_google.security.authenticator:
    class: GoogleBundle\Security\Authentication\Authenticator
         
  app_google.security.access_denied:
    class: GoogleBundle\Security\Authorization\AccessDeniedHandler
    arguments: ['@happyr.google.api.client']

  app_google.main_list_client:
    class: GoogleBundle\Service\MainListClient
    arguments: ['@happyr.google.api.client', '@security.token_storage']

  app_google.item_list_client:
    class: GoogleBundle\Service\ItemListClient
    arguments: ['@happyr.google.api.client', '@security.token_storage']

