USE uframework;

CREATE TABLE IF NOT EXISTS TASKLIST (
	ID int NOT NULL AUTO_INCREMENT,
	Nom varchar(100) NOT NULL,
	LimiteData DATETIME NOT NULL,
	Primary Key (ID) 
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS TASK (
	ID int NOT NULL AUTO_INCREMENT,
	Nom varchar(100) NOT NULL,
	Statut varchar(100) NOT NULL,
	TaskList_ID int NOT NULL,
	Primary Key (ID),
	FOREIGN KEY (TaskList_ID) REFERENCES TASKLIST(ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;
