<?php

namespace TodoListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemListRepository extends EntityRepository
{

}
