<?php

namespace TodoListBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * MainListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainListRepository extends EntityRepository
{
}
