#################
# Global Routes #
#################
app.index:
    path:  /
    defaults: { _controller: TodoListBundle:Default:index }

#########################################
# Routes for local ToDoList Application #
#########################################
app.list_index:
    path:  /local
    defaults: { _controller: TodoListBundle:List:list }

app.list_list:
    path:  /local/list
    defaults: { _controller: TodoListBundle:List:list }

app.list_list_add:
    path:  /local/list/add
    defaults: { _controller: TodoListBundle:List:listadd }

app.list_list_id:
    path:  /local/list/{id}
    defaults: { _controller: TodoListBundle:List:listid }
    requirements:
        id: \d+

app.list_list_edit:
    path:  /local/list/{id}/edit
    defaults: { _controller: TodoListBundle:List:listedit }
    requirements:
        id: \d+

app.list_list_remove:
    path:  /local/list/{id}/remove
    defaults: { _controller: TodoListBundle:List:listremove }
    requirements:
        id: \d+

app.item_item_add:
    path:  /local/list/{id}/item/add
    defaults: { _controller: TodoListBundle:Item:itemadd }
    requirements:
        id: \d+

app.item_item_id:
    path:  /local/list/{id}/item/{idItem}
    defaults: { _controller: TodoListBundle:Item:itemid }
    requirements:
        id: \d+
        idItem: \d+

app.item_item_edit:
    path:  /local/list/{id}/item/{idItem}/edit
    defaults: { _controller: TodoListBundle:Item:itemedit }
    requirements:
        id: \d+
        idItem: \d+

app.item_item_remove:
    path:  /local/list/{id}/item/{idItem}/remove
    defaults: { _controller: TodoListBundle:Item:itemremove }
    requirements:
        id: \d+
        idItem: \d+
