homepage:
    path: /
    defaults: { _controller : TodoListBundle:Default:index }
    
app:
    resource: "@TodoListBundle/Controller/"
    type: annotation

app.hello_hello:
    path: /hello/{name}
    defaults: { _controller: TodoListBundle:Default:hello }
    methods: [ GET ]
