# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    #encoders:
    #    Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern : ^/
            simple_preauth:
                authenticator : app_google.security.authenticator
            access_denied_handler: app_google.security.access_denied
    
    access_control:
        - { path: ^/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/google, roles: ROLE_OK }
        - { path: ^/google/$, roles: ROLE_OK }
